library(doBy)
library(data.table)
library(ggplot2)
library(cowplot)
library(RColorBrewer)
library(plyr)
library(gridGraphics)
library(plotly)
library(dplyr)
# Takes as input 1Mbp or 100kbp files generated by:
# calculate_gencov_windows.R, calculate_heterozygosityDiff_windows.R
# Produces a circlized plot over each chromosome/scaffold and plots genome 
# coverage against difference in heterozygosity
# USE WITH CAUTION OUTSIDE PIPELINE
# Call: Rscript {r-script} {gencov nm=first} {gencov nm=second} {gencov nm=third} 
# {difference in heterozygosity} {circlized out} {scatterplot out} {chr-list}

set.seed(999)

source("code/functions.R")
args <- commandArgs(trailingOnly = TRUE)

file1 = args[1]
file2 = args[2]
file3 = args[3]
filesnp = args[4]
absolute_out = args[5]
diff_out = args[6]
chr_file = args[7]
ED1 = args[8]
ED2 = args[9]
ED3 = args[10]
CHR_NR = args[11]

ED1 = gsub("\\.", "-", ED1)
ED2 = gsub("\\.", "-", ED2)
ED3 = gsub("\\.", "-", ED3)

ED1 = gsub("0-0", "0", ED1)
ED1 = gsub("0-", "<= ", ED1)
ED2 = gsub("0-", "<= ", ED2)


CHR_NR <- as.integer(CHR_NR)

file1_base = gsub(".out$", "", file1)
file2_base = gsub(".out$", "", file2)
file3_base = gsub(".out$", "", file3)
filesnp_base = gsub(".out$", "", filesnp)

diff_out_base = gsub("\\.pdf", ".png", diff_out)
absolute_out_base = gsub("\\.pdf", ".png", absolute_out)

################################################################################
################################# READ FILES ###################################
################################################################################

cov_1_table <- read.table(file1, 
                          header=TRUE, 
                          fill=TRUE, 
                          stringsAsFactor=FALSE)

cov_2_table <- read.table(file2, 
                          header=TRUE, 
                          fill=TRUE, 
                          stringsAsFactor=FALSE)

cov_3_table <- read.table(file3, 
                          header=TRUE, 
                          fill=TRUE, 
                          stringsAsFactor=FALSE)

snp_table   <- read.table(filesnp, 
                          header=TRUE, 
                          fill=TRUE, 
                          stringsAsFactor=FALSE)

# Mean and standard deviation calculation


if ( dim( cov_1_table )[1] == 0) {
  
  print("Warning: No chromosome/scaffold over 1Mbp or 100kbp! Check output based 
        on chromosome instead.")
  
} else {
  
  fun <- function(x){
    c(m=mean(x), s = sd(x))
  }
  
  sd_cov_1_table <- summaryBy(diff ~ 1 , data = cov_1_table, FUN = fun)
  sd_cov_2_table <- summaryBy(diff ~ 1 , data = cov_2_table, FUN = fun)
  sd_cov_3_table <- summaryBy(diff ~ 1 , data = cov_3_table, FUN = fun)
  sd_snp_table <- summaryBy(diff ~ 1 , data = snp_table, FUN = fun)
  
  if ( file.exists( chr_file ) ) {
    
    chromosome <- read.delim(chr_file, 
                             header = FALSE)
    chromosome <- chromosome$V1
    cov_1_table <- cov_1_table[ cov_1_table$chr %in% chromosome, ]
    cov_2_table <- cov_2_table[ cov_2_table$chr %in% chromosome, ]
    cov_3_table <- cov_3_table[ cov_3_table$chr %in% chromosome, ]
    snp_table <- snp_table[ snp_table$chr %in% chromosome, ]
    
  }
}


cov_1_table$diff_genome_mean <- sd_cov_1_table$diff.m
cov_1_table$diff_genome_sd <- sd_cov_1_table$diff.s
cov_2_table$diff_genome_mean <- sd_cov_2_table$diff.m
cov_2_table$diff_genome_sd <- sd_cov_2_table$diff.s
cov_3_table$diff_genome_mean <- sd_cov_3_table$diff.m
cov_3_table$diff_genome_sd <- sd_cov_3_table$diff.s
snp_table$diff_genome_mean <- sd_snp_table$diff.m
snp_table$diff_genome_sd <- sd_snp_table$diff.s

# Subset files for outlier (outside 95% CI) values
outlier.cov_1_table <- subset(cov_1_table, c(cov_1_table$diff > (cov_1_table$diff_genome_mean + cov_1_table$diff_genome_sd*2) | cov_1_table$diff < (cov_1_table$diff_genome_mean - cov_1_table$diff_genome_sd*2)))
outlier.cov_2_table <- subset(cov_2_table, c(cov_2_table$diff > (cov_2_table$diff_genome_mean + cov_2_table$diff_genome_sd*2) | cov_2_table$diff < (cov_2_table$diff_genome_mean - cov_2_table$diff_genome_sd*2)))
outlier.cov_3_table <- subset(cov_3_table, c(cov_3_table$diff > (cov_3_table$diff_genome_mean + cov_3_table$diff_genome_sd*2) | cov_3_table$diff < (cov_3_table$diff_genome_mean - cov_3_table$diff_genome_sd*2)))
outlier.snp_table <- subset(snp_table, c(snp_table$diff > (snp_table$diff_genome_mean + snp_table$diff_genome_sd*2) | snp_table$diff < (snp_table$diff_genome_mean - snp_table$diff_genome_sd*2)))

# Write outlier windows to tables
outname <- sprintf("%s.outlier.out", file1_base)
write.table(outlier.cov_1_table, file = outname, sep = "\t", quote = FALSE, row.names = F)
outname <- sprintf("%s.outlier.out", file2_base)
write.table(outlier.cov_2_table, file = outname, sep = "\t", quote = FALSE, row.names = F)
outname <- sprintf("%s.outlier.out", file3_base)
write.table(outlier.cov_3_table, file = outname, sep = "\t", quote = FALSE, row.names = F)
outname <- sprintf("%s.outlier.out", filesnp_base)
write.table(outlier.snp_table, file = outname, sep = "\t", quote = FALSE, row.names = F)


################################################################################
############################# ORDER CHROMOSOMES ################################
################################################################################

alldata <- rbind(cov_1_table, cov_2_table, cov_3_table, snp_table)


# Order after scaffold length if no chromosome file is given
if ( !file.exists(chr_file) ) {
  max_per_chr <- setDT( alldata )[, .SD[ which.max(range) ], 
                                  by=chr]
  max_per_chr <- as.data.frame( max_per_chr[,1:2] )
  chromosome <- max_per_chr[ order( -max_per_chr$range ), ][,1]
  len_chr <- dim(max_per_chr)[1]
} else { len_chr <- length(chromosome)

}


cov_1_table$chr <- ordered(cov_1_table$chr, 
                           levels = chromosome)
cov_2_table$chr <- ordered(cov_2_table$chr, 
                           levels = chromosome)
cov_3_table$chr <- ordered(cov_3_table$chr, 
                           levels = chromosome)
snp_table$chr <- ordered(snp_table$chr, 
                         levels = chromosome)


################################################################################
############################### MANHATTAN PLOT #################################
################################################################################

# Filter data for n longest scaffolds, determined by args[11]
if ( !file.exists(chr_file) & (len_chr > CHR_NR)) {
  nr_chr <- CHR_NR
  chromosome <- as.factor(chromosome[1:nr_chr])
} 

cov_1_table <- cov_1_table[cov_1_table$chr %in% chromosome,]
cov_2_table <- cov_2_table[cov_2_table$chr %in% chromosome,]
cov_3_table <- cov_3_table[cov_3_table$chr %in% chromosome,]
snp_table <- snp_table[snp_table$chr %in% chromosome,]


# Got code from here: https://www.r-graph-gallery.com/101_Manhattan_plot.html


colors <- c("heterogametic" = "darkgoldenrod1", "homogametic" = "darkmagenta")

# Prepare the dataset
cov1 <- cov_1_table %>% 
  # Compute chromosome size
  group_by(chr) %>% 
  summarise(chr_len=max(range)) %>% 
  # Calculate cumulative position of each chromosome
  mutate(tot=cumsum(chr_len)-chr_len) %>%
  select(-chr_len) %>%
  # Add this info to the initial dataset
  left_join(cov_1_table, ., by=c("chr"="chr")) %>%
  # Add a cumulative position of each SNP
  arrange(chr, range) %>%
  mutate( BPcum=range+tot)
# Prepare X axis
axisdf <- cov1 %>% group_by(chr) %>% summarize(center=( max(BPcum) + min(BPcum) ) / 2 )

# Make the plot
p.cov1 <- ggplot(cov1, aes(x=BPcum, y=diff)) +
  # custom X axis:
  scale_x_continuous( label = axisdf$chr, breaks= axisdf$center ) +
  scale_y_continuous(expand = c(0, 0) ) +     # remove space between plot area and x axis
  coord_cartesian(ylim=c(0, 2)) +
  ylab(sprintf("%s mismatches", ED1)) +
  geom_vline(aes(xintercept = tot), lty = 2, size = 0.2) +
  geom_point( aes(y = heterogametic, color="heterogametic"), alpha=0.2,size = 0.5 ) +
  geom_point( aes(y = homogametic, color="homogametic"), alpha=0.2,size = 0.5 ) +
  geom_smooth( aes(y = heterogametic, color="heterogametic", group = chr), method = 'gam', span = 0.3) +
  geom_smooth( aes(y = homogametic, color="homogametic", group = chr), method = 'gam', span = 0.3) +
  scale_color_manual(values = colors) +
  # Custom the theme:
  theme_bw() +
  theme( 
    legend.position="none",
    panel.border = element_blank(),
    axis.title.x = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)
  )+ theme(axis.text = element_text(size = 12)) + 
  theme(text=element_text(family="Helvetica"))+ theme(legend.title = element_blank()) + theme(legend.text = element_text(size=18, family="Helvetica")) + 
  theme(legend.key.height= unit(2, 'cm'),legend.key.width= unit(4, 'cm'))

# Prepare the dataset
cov2 <- cov_2_table %>% 
  # Compute chromosome size
  group_by(chr) %>% 
  summarise(chr_len=max(range)) %>% 
  # Calculate cumulative position of each chromosome
  mutate(tot=cumsum(chr_len)-chr_len) %>%
  select(-chr_len) %>%
  # Add this info to the initial dataset
  left_join(cov_2_table, ., by=c("chr"="chr")) %>%
  # Add a cumulative position of each SNP
  arrange(chr, range) %>%
  mutate( BPcum=range+tot)
# Prepare X axis
axisdf <- cov2 %>% group_by(chr) %>% summarize(center=( max(BPcum) + min(BPcum) ) / 2 )

# Make the plot
p.cov2 <- ggplot(cov2, aes(x=BPcum, y=diff)) +
  # custom X axis:
  scale_x_continuous( label = axisdf$chr, breaks= axisdf$center ) +
  scale_y_continuous(expand = c(0, 0) ) +     # remove space between plot area and x axis
  coord_cartesian(ylim=c(0, 2)) + 
  ylab(sprintf("%s mismatches", ED2)) +
  geom_vline(aes(xintercept = tot), lty = 2, size = 0.2) +
  geom_point( aes(y = heterogametic, color="heterogametic"), alpha=0.2,size = 0.5 ) +
  geom_point( aes(y = homogametic, color="homogametic"), alpha=0.2,size = 0.5 ) +
  geom_smooth( aes(y = heterogametic, color="heterogametic", group = chr), method = 'gam', span = 0.3) +
  geom_smooth( aes(y = homogametic, color="homogametic", group = chr), method = 'gam', span = 0.3) +
  scale_color_manual(values = colors) +
  # Custom the theme:
  theme_bw() +
  theme( 
    legend.position="none",
    panel.border = element_blank(),
    axis.title.x = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)
  )  +   theme(axis.text = element_text(size = 12)) + 
  theme(text=element_text(family="Helvetica"))+ theme(legend.title = element_blank()) + theme(legend.text = element_text(size=18, family="Helvetica")) + 
  theme(legend.key.height= unit(2, 'cm'),legend.key.width= unit(4, 'cm'))

# Prepare the dataset
cov3 <- cov_3_table %>% 
  # Compute chromosome size
  group_by(chr) %>% 
  summarise(chr_len=max(range)) %>% 
  # Calculate cumulative position of each chromosome
  mutate(tot=cumsum(chr_len)-chr_len) %>%
  select(-chr_len) %>%
  # Add this info to the initial dataset
  left_join(cov_3_table, ., by=c("chr"="chr")) %>%
  # Add a cumulative position of each SNP
  arrange(chr, range) %>%
  mutate( BPcum=range+tot)
# Prepare X axis
axisdf <- cov3 %>% group_by(chr) %>% summarize(center=( max(BPcum) + min(BPcum) ) / 2 )

# Make the plot
p.cov3 <- ggplot(cov3, aes(x=BPcum, y=diff)) +
  # custom X axis:
  scale_x_continuous( label = axisdf$chr, breaks= axisdf$center ) +
  scale_y_continuous(expand = c(0, 0) ) +     # remove space between plot area and x axis
  coord_cartesian(ylim=c(0, 2)) +
  ylab(sprintf("%s mismatches", ED3)) +
  geom_vline(aes(xintercept = tot), lty = 2, size = 0.2) +
  geom_point( aes(y = heterogametic, color="heterogametic"), alpha=0.2,size = 0.5 ) +
  geom_point( aes(y = homogametic, color="homogametic"), alpha=0.2,size = 0.5 ) +
  geom_smooth( aes(y = heterogametic, color="heterogametic", group = chr), method = 'gam', span = 0.3) +
  geom_smooth( aes(y = homogametic, color="homogametic", group = chr), method = 'gam', span = 0.3) +
  scale_color_manual(values = colors) +
  # Custom the theme:
  theme_bw() +
  theme( 
    legend.position="none",
    panel.border = element_blank(),
    axis.title.x = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)
  )+ theme(axis.text = element_text(size = 12)) + 
  theme(text=element_text(family="Helvetica"))+ theme(legend.title = element_blank()) + theme(legend.text = element_text(size=18, family="Helvetica")) + 
  theme(legend.key.height= unit(2, 'cm'),legend.key.width= unit(4, 'cm'))

# Prepare the dataset
snp <- snp_table %>% 
  # Compute chromosome size
  group_by(chr) %>% 
  summarise(chr_len=max(range)) %>% 
  # Calculate cumulative position of each chromosome
  mutate(tot=cumsum(chr_len)-chr_len) %>%
  select(-chr_len) %>%
  # Add this info to the initial dataset
  left_join(snp_table, ., by=c("chr"="chr")) %>%
  # Add a cumulative position of each SNP
  arrange(chr, range) %>%
  mutate( BPcum=range+tot)
# Prepare X axis
axisdf <- snp %>% group_by(chr) %>% summarize(center=( max(BPcum) + min(BPcum) ) / 2 )

# Make the plot
p.snp <- ggplot(snp, aes(x=BPcum, y=diff)) +
  # custom X axis:
  scale_x_continuous( label = axisdf$chr, breaks= axisdf$center ) +
  scale_y_continuous(expand = c(0, 0) ) +     # remove space between plot area and x axis
  coord_cartesian(ylim=c(0, 1)) +
  ylab("SNP diff") +
  geom_vline(aes(xintercept = tot), lty = 2, size = 0.2) +
  geom_point( aes(y = heterogametic, color="heterogametic"), alpha=0.2,size = 0.5 ) +
  geom_point( aes(y = homogametic, color="homogametic"), alpha=0.2,size = 0.5 ) +
  geom_smooth( aes(y = heterogametic, color="heterogametic", group = chr), method = 'gam', span = 0.3) +
  geom_smooth( aes(y = homogametic, color="homogametic", group = chr), method = 'gam', span = 0.3) +
  scale_color_manual(values = colors) +
  # Custom the theme:
  theme_bw() +
  theme( 
    # legend.position="none",
    panel.border = element_blank(),
    axis.title.x = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)
  ) + theme(axis.text = element_text(size = 12)) + 
  theme(text=element_text(family="Helvetica")) + theme(legend.title = element_blank()) + theme(legend.text = element_text(size=14, family="Helvetica")) + 
  theme(legend.key.height= unit(1, 'cm'),legend.key.width= unit(1, 'cm'), legend.key=element_rect(fill='white'))


#legend_b <- get_legend(p.snp + guides(color = guide_legend(nrow = 1)) + theme_bw() + theme(legend.position = "bottom")) 

legend_b <- get_legend(p.snp + theme(legend.position = "bottom", legend.key=element_rect(fill='white')))


c <- plot_grid(p.snp + theme(legend.position="none"), 
               p.cov1 + theme(legend.position="none"), 
               p.cov2 + theme(legend.position="none"), 
               p.cov3 + theme(legend.position="none"), 
               nrow = 4, 
               labels = c("A","B","C", "D"))


d <- plot_grid(c, legend_b, ncol = 1, rel_heights = c(1, .1))

#pdf(file=absolute_out, width = 15, height = 10)
pdf(file=absolute_out, width = 13, height = 7)
print(d)
dev.off()


png(file=absolute_out_base, width = 1100, height = 600)
print(d)
dev.off()

absolute_out_base = gsub("\\.pdf", "", absolute_out)
ggsave(sprintf("%s.png", diff_out_base), plot = d, device = png(), width = 14, height = 8, dpi = 900)

############### DIFF


# Make the plot
b <- c(sd_cov_1_table$diff.m-(sd_cov_1_table$diff.s*2), sd_cov_1_table$diff.m, (sd_cov_1_table$diff.m+sd_cov_1_table$diff.s*2))
p.cov1 <- ggplot(cov1, aes(x=BPcum, y=diff, color = diff)) +
  # custom X axis:
  scale_x_continuous( label = axisdf$chr, breaks= axisdf$center ) +
  scale_y_continuous(expand = c(0, 0) ) +     # remove space between plot area and x axis
  coord_cartesian(ylim=c(-1, 1)) +
  ylab(sprintf("%s mismatches", ED1)) +
  labs(color = "95 % CI") +
  geom_vline(aes(xintercept = tot), lty = 2, size = 0.2) +
  geom_point(alpha=0.8, size=1.5) +
  scale_color_gradientn(limits = c(-1,1), colours=c("blue", "grey40", "red"),breaks=b, labels=format(b)) + 
  theme_bw() +
  theme( 
    # legend.position="none",
    panel.border = element_blank(),
    axis.title.x = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)
  ) + guides(fill = guide_colourbar(barwidth = 0.5, barheight = 10))+ 
  theme(axis.text = element_text(size = 12)) + 
  theme(text=element_text(family="Helvetica"))


# Make the plot
b <- c(sd_cov_2_table$diff.m-(sd_cov_2_table$diff.s*2), sd_cov_2_table$diff.m, (sd_cov_2_table$diff.m+sd_cov_2_table$diff.s*2))
p.cov2 <- ggplot(cov2, aes(x=BPcum, y=diff, color = diff)) +
  # custom X axis:
  scale_x_continuous( label = axisdf$chr, breaks= axisdf$center ) +
  scale_y_continuous(expand = c(0, 0) ) +     # remove space between plot area and x axis
  coord_cartesian(ylim=c(-1, 1)) +
  ylab(sprintf("%s mismatches", ED2)) +
  labs(color = "95 % CI") +
  geom_vline(aes(xintercept = tot), lty = 2, size = 0.2) +
  geom_point(alpha=0.8, size=1.5) +
  scale_color_gradientn(limits = c(-1,1), colours=c("blue", "grey40", "red"),breaks=b, labels=format(b)) + 
  theme_bw() +
  theme( 
    # legend.position="none",
    panel.border = element_blank(),
    axis.title.x = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + 
  guides(fill = guide_colourbar(barwidth = 0.5, barheight = 10))+ 
  theme(axis.text = element_text(size = 12)) + 
  theme(text=element_text(family="Helvetica"))

# Make the plot
b <- c(sd_cov_3_table$diff.m-(sd_cov_3_table$diff.s*2), sd_cov_3_table$diff.m, (sd_cov_3_table$diff.m+sd_cov_3_table$diff.s*2))
p.cov3 <- ggplot(cov3, aes(x=BPcum, y=diff, color = diff)) +
  # custom X axis:
  scale_x_continuous( label = axisdf$chr, breaks= axisdf$center ) +
  scale_y_continuous(expand = c(0, 0) ) +     # remove space between plot area and x axis
  coord_cartesian(ylim=c(-1, 1)) +
  ylab(sprintf("%s mismatches", ED3)) +
  labs(color = "95 % CI") +
  geom_vline(aes(xintercept = tot), lty = 2, size = 0.2) +
  geom_point(alpha=0.8, size=1.5) +
  scale_color_gradientn(limits = c(-1,1), colours=c("blue", "grey40", "red"),breaks=b, labels=format(b)) + 
  theme_bw() +
  theme( 
    # legend.position="none",
    panel.border = element_blank(),
    axis.title.x = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+ 
    guides(fill = guide_colourbar(barwidth = 0.5, barheight = 10))+ 
    theme(axis.text = element_text(size = 12)) + 
    theme(text=element_text(family="Helvetica"))



b <- c(sd_snp_table$diff.m-(sd_snp_table$diff.s*2), sd_snp_table$diff.m, (sd_snp_table$diff.m+sd_snp_table$diff.s*2))
# Make the plot
p.snp <- ggplot(snp, aes(x=BPcum, y=diff, color = diff)) +
  # custom X axis:
  scale_x_continuous( label = axisdf$chr, breaks= axisdf$center ) +
  scale_y_continuous(expand = c(0, 0) ) +     # remove space between plot area and x axis
  coord_cartesian(ylim=c(-1, 1)) +
  ylab("SNP diff") +
  labs(color = "95 % CI") +
  geom_vline(aes(xintercept = tot), lty = 2, size = 0.2) +
  geom_point(alpha=0.8, size=1.5) +
  scale_color_gradientn(limits = c(-1,1), colours=c("blue", "grey40", "red"),breaks=b, labels=format(b)) + 
  theme_bw() +
  theme( 
    # legend.position="none",
    panel.border = element_blank(),
    axis.title.x = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+ 
    guides(fill = guide_colourbar(barwidth = 0.5, barheight = 10))+ 
    theme(axis.text = element_text(size = 12)) + 
    theme(text=element_text(family="Helvetica"))


c <- plot_grid(p.snp, 
               p.cov1, 
               p.cov2, 
               p.cov3, 
               nrow = 4, align = "v", 
               labels = c("A","B","C", "D"))

#d <- plot_grid(c, legend_b, ncol = 1, rel_heights = c(1, .1))

pdf(file=diff_out, width = 14, height = 7)
#pdf(file="test.pdf", width = 15, height = 9)
print(c)
dev.off()

png(file=diff_out_base, width = 1000, height = 600)
print(c)
dev.off()


diff_out_base = gsub("\\.pdf", "", diff_out)
ggsave(sprintf("%s.png", diff_out_base), plot = c, device = png(), width = 14, height = 8, dpi = 900)



absolute_out_tiff = gsub("\\.pdf", ".tiff", absolute_out)
tiff(file=absolute_out_tiff, width = 1000, height = 600)
print(c)
dev.off()
