library(doBy)
library(data.table)
library(ggplot2)
library(cowplot)
library(RColorBrewer)
library(plyr)
library(gridGraphics)
library(plotly)
library(dplyr)
# Takes as input 1Mbp or 100kbp files generated by:
# calculate_gencov_windows.R, calculate_heterozygosityDiff_windows.R
# Produces a circlized plot over each chromosome/scaffold and plots genome 
# coverage against difference in heterozygosity
# USE WITH CAUTION OUTSIDE PIPELINE
# Call: Rscript {r-script} {gencov nm=first} {gencov nm=second} {gencov nm=third} 
# {difference in heterozygosity} {circlized out} {scatterplot out} {chr-list}

set.seed(999)

source("code/functions.R")
args <- commandArgs(trailingOnly = TRUE)

file1 = args[1]
file2 = args[2]
file3 = args[3]
filesnp = args[4]
absolute_out = args[5]
diff_out = args[6]
chr_file = args[7]
ED1 = args[8]
ED2 = args[9]
ED3 = args[10]
CHR_NR = args[11]

#setwd("~/Dropbox (MEEL)/PhD/Subprojects/6 Sylvioidea neosc-scan/9 Sexchromoscanner/code/")
#file1 = "../results/bella/aloatta/aloatta.HS.gencov.nodup.nm.0.0.1Mbp.out"
#file2 = "../results/bella/aloatta/aloatta.HS.gencov.nodup.nm.0.2.1Mbp.out"
#file3 = "../results/bella/aloatta/aloatta.HS.gencov.nodup.nm.all.1Mbp.out"
#filesnp = "../results/bella/aloatta/aloatta.HS.diffHeterozygosity.1Mbp.out"
#circlize_out = "test.circlize.pdf"
#scatter_out = "test.scatter.pdf"
#chr_file = "hello.txt"
#source("functions.R")
#ED1 = "0.0"
#ED2 = "0.2"
#ED3 = "all"
#CHR_NR = 5

ED1 = gsub("\\.", "-", ED1)
ED2 = gsub("\\.", "-", ED2)
ED3 = gsub("\\.", "-", ED3)

################################################################################
################################# READ FILES ###################################
################################################################################


cov_1_table <- read.table(file1, 
                          header=TRUE, 
                          fill=TRUE, 
                          stringsAsFactor=FALSE)

cov_2_table <- read.table(file2, 
                          header=TRUE, 
                          fill=TRUE, 
                          stringsAsFactor=FALSE)

cov_3_table <- read.table(file3, 
                          header=TRUE, 
                          fill=TRUE, 
                          stringsAsFactor=FALSE)

snp_table   <- read.table(filesnp, 
                          header=TRUE, 
                          fill=TRUE, 
                          stringsAsFactor=FALSE)

if ( dim( cov_1_table )[1] == 0) {
  
  print("Warning: No chromosome/scaffold over 1Mbp or 11kbp! Check output based 
        on chromosome instead.")
  
} else {
  
  if ( file.exists( chr_file ) ) {
    
    chromosome <- read.csv(chr_file, 
                           header = FALSE, 
                           sep = ",")
    
    cov_1_table <- cov_1_table[ cov_1_table$chr %in% chromosome, ]
    
  }
}




################################################################################
############################# ORDER CHROMOSOMES ################################
################################################################################

alldata <- rbind(cov_1_table, cov_2_table, cov_3_table, snp_table)


# Order after scaffold length if no chromosome file is given
if ( !file.exists(chr_file) ) {
  max_per_chr <- setDT( alldata )[, .SD[ which.max(range) ], 
                                  by=chr]
  max_per_chr <- as.data.frame( max_per_chr[,1:2] )
  chromosome <- max_per_chr[ order( -max_per_chr$range ), ][,1]

}

len_chr <- as.data.frame( max_per_chr[,1:2])

cov_1_table$chr <- ordered( cov_1_table$chr, 
                            levels = chromosome)
cov_2_table$chr <- ordered( cov_2_table$chr, 
                            levels = chromosome)
cov_3_table$chr <- ordered( cov_3_table$chr, 
                            levels = chromosome)
snp_table$chr <- ordered( snp_table$chr, 
                          levels = chromosome)




# Filter data for n longest scaffolds, determined by args[11]
if ( !file.exists(chr_file) & dim(len_chr)[1] >= CHR_NR) {
  nr_chr <- CHR_NR
} else {
  nr_chr <- dim(len_chr)[1]
  chromosome <- as.factor(len_chr[with(len_chr, order(-range)),][1:nr_chr,1])
}



cov_1_table <- cov_1_table[cov_1_table$chr %in% chromosome,]
cov_2_table <- cov_2_table[cov_2_table$chr %in% chromosome,]
cov_3_table <- cov_3_table[cov_3_table$chr %in% chromosome,]
snp_table <- snp_table[snp_table$chr %in% chromosome,]


# Mean and standard deviation calculation
fun <- function(x){
  c(m=mean(x), s = sd(x))
}

sd_cov_1_table <- summaryBy(diff ~ 1 , data = cov_1_table, FUN = fun)
sd_cov_2_table <- summaryBy(diff ~ 1 , data = cov_2_table, FUN = fun)
sd_cov_3_table <- summaryBy(diff ~ 1 , data = cov_3_table, FUN = fun)
sd_snp_table <- summaryBy(diff ~ 1 , data = snp_table, FUN = fun)

################################################################################
############################### MANHATTAN PLOT #################################
################################################################################



# Got code from here: https://www.r-graph-gallery.com/101_Manhattan_plot.html



colors <- c("heterogametic" = "darkgoldenrod1", "homogametic" = "darkmagenta")

# Prepare the dataset
cov1 <- cov_1_table %>% 
  # Compute chromosome size
  group_by(chr) %>% 
  summarise(chr_len=max(range)) %>% 
  # Calculate cumulative position of each chromosome
  mutate(tot=cumsum(chr_len)-chr_len) %>%
  select(-chr_len) %>%
  # Add this info to the initial dataset
  left_join(cov_1_table, ., by=c("chr"="chr")) %>%
  # Add a cumulative position of each SNP
  arrange(chr, range) %>%
  mutate( BPcum=range+tot)
# Prepare X axis
axisdf <- cov1 %>% group_by(chr) %>% summarize(center=( max(BPcum) + min(BPcum) ) / 2 )

# Make the plot
p.cov1 <- ggplot(cov1, aes(x=BPcum, y=diff)) +
  # custom X axis:
  scale_x_continuous( label = axisdf$chr, breaks= axisdf$center ) +
  scale_y_continuous(expand = c(0, 0) ) +     # remove space between plot area and x axis
  coord_cartesian(ylim=c(0, 2)) +
 # geom_rect(mapping=aes(xmin=-Inf, xmax=Inf, ymin=se_cov_1_table$ratio.m-se_cov_1_table$ratio.s, ymax=se_cov_1_table$ratio.m+se_cov_1_table$ratio.s), fill="pink", alpha=0.5) +
  ylab(sprintf("%s mismatches", ED1)) +
  geom_vline(aes(xintercept = tot), lty = 2, size = 0.2) +
  geom_point( aes(y = heterogametic, color="heterogametic"), alpha=0.2,size = 0.5 ) +
  geom_point( aes(y = homogametic, color="homogametic"), alpha=0.2,size = 0.5 ) +
  geom_smooth( aes(y = heterogametic, color="heterogametic", group = chr), method = 'loess', span = 0.3) +
  geom_smooth( aes(y = homogametic, color="homogametic", group = chr), method = 'loess', span = 0.3) +
  #geom_point( aes(color=as.factor(chr)), alpha=0.8, size=1) +
  #scale_color_manual(values = rep(c("darkgrey", "black"), 50 )) +
  scale_color_manual(values = colors) +
  # Custom the theme:
  theme_bw() +
  theme( 
    legend.position="none",
    panel.border = element_blank(),
    axis.title.x = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)
  )

# Prepare the dataset
cov2 <- cov_2_table %>% 
  # Compute chromosome size
  group_by(chr) %>% 
  summarise(chr_len=max(range)) %>% 
  # Calculate cumulative position of each chromosome
  mutate(tot=cumsum(chr_len)-chr_len) %>%
  select(-chr_len) %>%
  # Add this info to the initial dataset
  left_join(cov_2_table, ., by=c("chr"="chr")) %>%
  # Add a cumulative position of each SNP
  arrange(chr, range) %>%
  mutate( BPcum=range+tot)
# Prepare X axis
axisdf <- cov2 %>% group_by(chr) %>% summarize(center=( max(BPcum) + min(BPcum) ) / 2 )

# Make the plot
p.cov2 <- ggplot(cov2, aes(x=BPcum, y=diff)) +
  # custom X axis:
  scale_x_continuous( label = axisdf$chr, breaks= axisdf$center ) +
  scale_y_continuous(expand = c(0, 0) ) +     # remove space between plot area and x axis
  coord_cartesian(ylim=c(0, 2)) + 
 # geom_rect(mapping=aes(xmin=-Inf, xmax=Inf, ymin=se_cov_2_table$ratio.m-se_cov_2_table$ratio.s, ymax=se_cov_2_table$ratio.m+se_cov_2_table$ratio.s), fill="pink", alpha=0.5) +
  ylab(sprintf("%s mismatches", ED2)) +
  geom_vline(aes(xintercept = tot), lty = 2, size = 0.2) +
  geom_point( aes(y = heterogametic, color="heterogametic"), alpha=0.2,size = 0.5 ) +
  geom_point( aes(y = homogametic, color="homogametic"), alpha=0.2,size = 0.5 ) +
  geom_smooth( aes(y = heterogametic, color="heterogametic", group = chr), method = 'loess', span = 0.3) +
  geom_smooth( aes(y = homogametic, color="homogametic", group = chr), method = 'loess', span = 0.3) +
  #geom_point( aes(color=as.factor(chr)), alpha=0.8, size=1) +
  #scale_color_manual(values = rep(c("darkgrey", "black"), 50 )) +
  scale_color_manual(values = colors) +
  # Custom the theme:
  theme_bw() +
  theme( 
    legend.position="none",
    panel.border = element_blank(),
    axis.title.x = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)
  ) 

# Prepare the dataset
cov3 <- cov_3_table %>% 
  # Compute chromosome size
  group_by(chr) %>% 
  summarise(chr_len=max(range)) %>% 
  # Calculate cumulative position of each chromosome
  mutate(tot=cumsum(chr_len)-chr_len) %>%
  select(-chr_len) %>%
  # Add this info to the initial dataset
  left_join(cov_3_table, ., by=c("chr"="chr")) %>%
  # Add a cumulative position of each SNP
  arrange(chr, range) %>%
  mutate( BPcum=range+tot)
# Prepare X axis
axisdf <- cov3 %>% group_by(chr) %>% summarize(center=( max(BPcum) + min(BPcum) ) / 2 )

# Make the plot
p.cov3 <- ggplot(cov3, aes(x=BPcum, y=diff)) +
  # custom X axis:
  scale_x_continuous( label = axisdf$chr, breaks= axisdf$center ) +
  scale_y_continuous(expand = c(0, 0) ) +     # remove space between plot area and x axis
  coord_cartesian(ylim=c(0, 2)) +
 # geom_rect(mapping=aes(xmin=-Inf, xmax=Inf, ymin=se_cov_3_table$ratio.m-se_cov_3_table$ratio.s, ymax=se_cov_3_table$ratio.m+se_cov_3_table$ratio.s), fill="pink", alpha=0.5) +
  ylab(sprintf("%s mismatches", ED3)) +
  geom_vline(aes(xintercept = tot), lty = 2, size = 0.2) +
  geom_point( aes(y = heterogametic, color="heterogametic"), alpha=0.2,size = 0.5 ) +
  geom_point( aes(y = homogametic, color="homogametic"), alpha=0.2,size = 0.5 ) +
  geom_smooth( aes(y = heterogametic, color="heterogametic", group = chr), method = 'loess', span = 0.3) +
  geom_smooth( aes(y = homogametic, color="homogametic", group = chr), method = 'loess', span = 0.3) +
  #geom_point( aes(color=as.factor(chr)), alpha=0.8, size=1) +
  #scale_color_manual(values = rep(c("darkgrey", "black"), 50 )) +
  scale_color_manual(values = colors) +
  # Custom the theme:
  theme_bw() +
  theme( 
    legend.position="none",
    panel.border = element_blank(),
    axis.title.x = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)
  )

# Prepare the dataset
snp <- snp_table %>% 
  # Compute chromosome size
  group_by(chr) %>% 
  summarise(chr_len=max(range)) %>% 
  # Calculate cumulative position of each chromosome
  mutate(tot=cumsum(chr_len)-chr_len) %>%
  select(-chr_len) %>%
  # Add this info to the initial dataset
  left_join(snp_table, ., by=c("chr"="chr")) %>%
  # Add a cumulative position of each SNP
  arrange(chr, range) %>%
  mutate( BPcum=range+tot)
# Prepare X axis
axisdf <- snp %>% group_by(chr) %>% summarize(center=( max(BPcum) + min(BPcum) ) / 2 )

# Make the plot
p.snp <- ggplot(snp, aes(x=BPcum, y=diff)) +
  # custom X axis:
  scale_x_continuous( label = axisdf$chr, breaks= axisdf$center ) +
  scale_y_continuous(expand = c(0, 0) ) +     # remove space between plot area and x axis
  coord_cartesian(ylim=c(0, 1)) +
  ylab("SNP diff") +
  geom_vline(aes(xintercept = tot), lty = 2, size = 0.2) +
  geom_point( aes(y = heterogametic, color="heterogametic"), alpha=0.2,size = 0.5 ) +
  geom_point( aes(y = homogametic, color="homogametic"), alpha=0.2,size = 0.5 ) +
  geom_smooth( aes(y = heterogametic, color="heterogametic", group = chr), method = 'loess', span = 0.3) +
  geom_smooth( aes(y = homogametic, color="homogametic", group = chr), method = 'loess', span = 0.3) +
  #geom_point( aes(color=as.factor(chr)), alpha=0.8, size=1) +
  #scale_color_manual(values = rep(c("darkgrey", "black"), 50 )) +
  scale_color_manual(values = colors) +
  # Custom the theme:
  theme_bw() +
  theme( 
    # legend.position="none",
    panel.border = element_blank(),
    axis.title.x = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)
  )


legend_b <- get_legend(p.snp + guides(color = guide_legend(nrow = 1)) + theme_bw() + theme(legend.position = "bottom"))


c <- plot_grid(p.snp + theme(legend.position="none"), 
               p.cov1 + theme(legend.position="none"), 
               p.cov2 + theme(legend.position="none"), 
               p.cov3 + theme(legend.position="none"), 
               nrow = 4, 
               labels = c("A","B","C", "D"))


d <- plot_grid(c, legend_b, ncol = 1, rel_heights = c(1, .1))

pdf(file=absolute_out, width = 9, height = 5)
#pdf(file="test.pdf", width = 9, height = 5)
print(d)
dev.off()




############### DIFF


# Make the plot
b <- c(sd_cov_1_table$diff.m-(sd_cov_1_table$diff.s*2), sd_cov_1_table$diff.m, (sd_cov_1_table$diff.m+sd_cov_1_table$diff.s*2))
p.cov1 <- ggplot(cov1, aes(x=BPcum, y=diff, color = diff)) +
  # custom X axis:
  scale_x_continuous( label = axisdf$chr, breaks= axisdf$center ) +
  scale_y_continuous(expand = c(0, 0) ) +     # remove space between plot area and x axis
  coord_cartesian(ylim=c(-1, 1)) +
  ylab(sprintf("%s mismatches", ED1)) +
  labs(color = "95 % CI") +
  geom_vline(aes(xintercept = tot), lty = 2, size = 0.2) +
  geom_point(alpha=0.8, size=1) +
  scale_color_gradientn(limits = c(-1,1), colours=c("blue", "grey", "red"),breaks=b, labels=format(b)) + 
  theme_bw() +
  theme( 
   # legend.position="none",
    panel.border = element_blank(),
    axis.title.x = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)
  )


# Make the plot
b <- c(sd_cov_2_table$diff.m-(sd_cov_2_table$diff.s*2), sd_cov_2_table$diff.m, (sd_cov_2_table$diff.m+sd_cov_2_table$diff.s*2))
p.cov2 <- ggplot(cov2, aes(x=BPcum, y=diff, color = diff)) +
  # custom X axis:
  scale_x_continuous( label = axisdf$chr, breaks= axisdf$center ) +
  scale_y_continuous(expand = c(0, 0) ) +     # remove space between plot area and x axis
  coord_cartesian(ylim=c(-1, 1)) +
  ylab(sprintf("%s mismatches", ED2)) +
  labs(color = "95 % CI") +
  geom_vline(aes(xintercept = tot), lty = 2, size = 0.2) +
  geom_point(alpha=0.8, size=1) +
  scale_color_gradientn(limits = c(-1,1), colours=c("blue", "grey", "red"),breaks=b, labels=format(b)) + 
  theme_bw() +
  theme( 
   # legend.position="none",
    panel.border = element_blank(),
    axis.title.x = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)
  ) 

# Make the plot
b <- c(sd_cov_3_table$diff.m-(sd_cov_3_table$diff.s*2), sd_cov_3_table$diff.m, (sd_cov_3_table$diff.m+sd_cov_3_table$diff.s*2))
p.cov3 <- ggplot(cov3, aes(x=BPcum, y=diff, color = diff)) +
  # custom X axis:
  scale_x_continuous( label = axisdf$chr, breaks= axisdf$center ) +
  scale_y_continuous(expand = c(0, 0) ) +     # remove space between plot area and x axis
  coord_cartesian(ylim=c(-1, 1)) +
  ylab(sprintf("%s mismatches", ED3)) +
  labs(color = "95 % CI") +
  geom_vline(aes(xintercept = tot), lty = 2, size = 0.2) +
  geom_point(alpha=0.8, size=1) +
  scale_color_gradientn(limits = c(-1,1), colours=c("blue", "grey", "red"),breaks=b, labels=format(b)) + 
  theme_bw() +
  theme( 
   # legend.position="none",
    panel.border = element_blank(),
    axis.title.x = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)
  )



b <- c(sd_snp_table$diff.m-(sd_snp_table$diff.s*2), sd_snp_table$diff.m, (sd_snp_table$diff.m+sd_snp_table$diff.s*2))
# Make the plot
p.snp <- ggplot(snp, aes(x=BPcum, y=diff, color = diff)) +
  # custom X axis:
  scale_x_continuous( label = axisdf$chr, breaks= axisdf$center ) +
  scale_y_continuous(expand = c(0, 0) ) +     # remove space between plot area and x axis
  coord_cartesian(ylim=c(-1, 1)) +
  ylab("SNP diff") +
  labs(color = "95 % CI") +
  geom_vline(aes(xintercept = tot), lty = 2, size = 0.2) +
  geom_point(alpha=0.8, size=1) +
  scale_color_gradientn(limits = c(-1,1), colours=c("blue", "grey", "red"),breaks=b, labels=format(b)) + 
  theme_bw() +
  theme( 
    # legend.position="none",
    panel.border = element_blank(),
    axis.title.x = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)
  )


c <- plot_grid(p.snp, 
               p.cov1, 
               p.cov2, 
               p.cov3, 
               nrow = 4, align = "v", 
               labels = c("A","B","C", "D"))

#d <- plot_grid(c, legend_b, ncol = 1, rel_heights = c(1, .1))

pdf(file=diff_out, width = 15, height = 12)
#pdf(file="test.pdf", width = 15, height = 9)
print(c)
dev.off()

