# Specify max number of cores
threads_max: 2


# Path to sample information file
units: config/Datasets/Drosophila_units.tsv

# Name of analysis. The result files will be stored under "results/{run_name}"
run_name: "DroMir_test" 

# Homogametic reference genome of the studied species (not .gz format)
ref_genome: "data/genome/GCA_000269505.2_DroMir_2.2.fasta" 

# List of chromosomes that should be plotted (and highlighted) in the end (optional) 
chr_file: "None"
chr_highlight:
    - CM001517.2 # Chromosomes to be highlighted. Remove if not wanted.
    - CM001519.2
    - CM001516.2
trim_reads: TRUE # Set to TRUE if you want to trim reads
#sra_download: TRUE # Set to TRUE if you want to trim reads


############# snakefile-synteny variables #############

# If snakemake-synteny is used, specify the path to the synteny-species reference genome (not .gz format)
synteny_ref: ".test/Example/Homo_sapiens.GRCh38_subset.fasta"

# Synteny-species abbreviation (can be anything)
synteny_abbr: "HS"

# List of chromosomes in the synteny-species reference genome that should be plotted (and highlighted) in the end (optional) 
synteny_chr_file: config/HS_chromosomes.list
synteny_chr_highlight: config/HS_chromosomes_highlight.list


############# Other optional variables ##########

# The pipeline will produce genome coverage results based on three different mismatches criteria. 
# The first two variables can be edited. 
edit_distance:
    - 0.0 # 0 mismatches allowed
    - 0.2 # <=2 mismatches allowed
    - unfiltered # Do not edit this one

window_sizes:
    - 100000
    - 1000000

# The Mimimum size of scaffolds in the reference genome to be considered. 
minSizeScaffold: "10000"


# Software-specific settings. Modify if needed. 
params:
  picard:
    MarkDuplicates: 
        - "REMOVE_DUPLICATES=true"
        - "USE_JDK_DEFLATER=true" 
        - "USE_JDK_INFLATER=true"
        - "-Xmx2g"
  trimmomatic:
    pe:
      trimmer:
        - "LEADING:3"
        - "TRAILING:3"
        - "SLIDINGWINDOW:4:15"
        - "MINLEN:36"
        - "ILLUMINACLIP:data/adapters/TruSeq3-PE.fa:2:30:10"
    se:
      trimmer:
        - "LEADING:3"
        - "TRAILING:3"
        - "SLIDINGWINDOW:4:15"
        - "MINLEN:36"
        - "ILLUMINACLIP:data/adapters/TruSeq3-PE.fa:2:30:10"


