#samples: config/samples.tsv
units: config/units.tsv

chr_file: config/chromosomes.list
chr_highlight: config/chromosomes_highlight.list

#processing:
#  remove-duplicates: true

params:
  picard:
    MarkDuplicates: 
        - "REMOVE_DUPLICATES=true"
        - "USE_JDK_DEFLATER=true" 
        - "USE_JDK_INFLATER=true"
  trimmomatic:
    pe:
      trimmer:
        - "LEADING:3"
        - "TRAILING:3"
        - "SLIDINGWINDOW:4:15"
        - "MINLEN:36"
        - "ILLUMINACLIP:data/adapters/TruSeq3-PE.fa:2:30:10"
    se:
      trimmer:
        - "LEADING:3"
        - "TRAILING:3"
        - "SLIDINGWINDOW:4:15"
        - "MINLEN:36"
        - "ILLUMINACLIP:data/adapters/TruSeq3-PE.fa:2:30:10"


edit_distance:
    - 0.0
    - 0.2
    - all
minSizeScaffold: "10000"