#samples: config/samples.tsv
units: config/units.tsv


run_name: "AloPal_test"
ref_genome: ".test/Example/AloPal_v1_subset.fasta"


chr_file: config/chromosomes.list
chr_highlight: config/chromosomes_highlight.list

synteny_ref: ".test/Example/Homo_sapiens.GRCh38_subset.fasta"
synteny_abbr: "HS"
synteny_chr_file: config/HS_chromosomes.list
synteny_chr_highlight: config/HS_chromosomes_highlight.list

#processing:
#  remove-duplicates: true

params:
  picard:
    MarkDuplicates: 
        - "REMOVE_DUPLICATES=true"
        - "USE_JDK_DEFLATER=true" 
        - "USE_JDK_INFLATER=true"
  trimmomatic:
    pe:
      trimmer:
        - "LEADING:3"
        - "TRAILING:3"
        - "SLIDINGWINDOW:4:15"
        - "MINLEN:36"
        - "ILLUMINACLIP:data/adapters/TruSeq3-PE.fa:2:30:10"
    se:
      trimmer:
        - "LEADING:3"
        - "TRAILING:3"
        - "SLIDINGWINDOW:4:15"
        - "MINLEN:36"
        - "ILLUMINACLIP:data/adapters/TruSeq3-PE.fa:2:30:10"


edit_distance:
    - 0.0
    - 0.2
    - all
minSizeScaffold: "10000"