# Specify max number of cores
threads_max: 2


# Path to sample information file
units: config/units.tsv

# Name of analysis. The result files will be stored under "results/{run_name}"
run_name: "AloPal_test" 

# Homogametic reference genome of the studied species (not .gz format)
ref_genome: ".test/Example/AloPal_v1_subset.fasta" 

# List of chromosomes that should be plotted (and highlighted) in the end (optional) 
chr_file: config/chromosomes.list
chr_highlight: config/chromosomes_highlight.list
trim_reads: FALSE # Set to TRUE if you want to trim reads

############# snakefile-synteny variables #############

# If snakemake-synteny is used, specify the path to the synteny-species reference genome (not .gz format)
synteny_ref: ".test/Example/Homo_sapiens.GRCh38_subset.fasta"

# Synteny-species abbreviation (can be anything)
synteny_abbr: "HS"

# List of chromosomes in the synteny-species reference genome that should be plotted (and highlighted) in the end (optional) 
synteny_chr_file: config/HS_chromosomes.list
synteny_chr_highlight: config/HS_chromosomes_highlight.list


############# Other optional variables ##########

# The pipeline will produce genome coverage results based on three different mismatches criteria. 
# The first two variables can be edited. 
edit_distance:
    - 0.0 # 0 mismatches allowed
    - 0.2 # <=2 mismatches allowed
    - all # Do not edit this one


# The Mimimum size of scaffolds in the reference genome to be considered. 
minSizeScaffold: "10000"


# Software-specific settings. Modify if needed. 
params:
  picard:
    MarkDuplicates: 
        - "REMOVE_DUPLICATES=true"
        - "USE_JDK_DEFLATER=true" 
        - "USE_JDK_INFLATER=true"
        - "-Xmx2g"
  trimmomatic:
    pe:
      trimmer:
        - "LEADING:3"
        - "TRAILING:3"
        - "SLIDINGWINDOW:4:15"
        - "MINLEN:36"
        - "ILLUMINACLIP:data/adapters/TruSeq3-PE.fa:2:30:10"
    se:
      trimmer:
        - "LEADING:3"
        - "TRAILING:3"
        - "SLIDINGWINDOW:4:15"
        - "MINLEN:36"
        - "ILLUMINACLIP:data/adapters/TruSeq3-PE.fa:2:30:10"


