## =================== ##
## findZX config file  ##
## =================== ##

# Variables marked with "[findZX]" or "[findZX-synteny]" are only used when deploying 
# the pipeline with either snakefile. Other variables are used for all analyses. 

threads_max: 18
mem_max: 8000 
  # Specify maximum number of cores [threads_max] and memory [mem_max] allocation


# ============================ #
# Analysis name and input data #

run_name: Pogona_vitticeps 
  # Select an analysis name. Output files will be stored under "results/[run_name]"

units: config/9_species_config/Pogona_vitticeps_units.tsv
  # Path to sample information file

ref_genome: ../data/external_raw/genome/Pogona_vitticeps.fasta 
  # Path to study-species reference genome (not .gz format)

synteny_ref: ../data/external_raw/genome/Gallus_gallus.GRCg6a.dna.toplevel.noW.fa
  # [findZX-synteny] Path to synteny-species reference genome (not .gz format)

synteny_name: GG
  # [findZX-synteny] Synteny-species name (can be any string, will be used for file and directory names)


# ================= #
# Plotting settings #

window_sizes: [50000, 100000, 1000000]
  # Choose genome window sizes for plotting (as many as you want)
  # Optimal sizes depend on reference genome fragmentation and size of the sex-linked region
  # Recommended sizes to start are: [50000, 100000, 1000000] (i.e. 50 kb, 100 kb, 1Mb)

chr_file: None
  # [findZX] Specify a file with list of chromosomes to only plot these (otherwise leave as "None")

chr_highlight: [CEMB01002638.1, CEMB01011940.1, CEMB01037558.1, CEMB01017046.1]
  # [findZX] Specify chromosomes/scaffolds to highlight in plot type 4, or leave empty

# NW_018150872.1  = contig2638 = CEMB01002638.1 = scf000179
# NW_018150853.1 = contig11940 = scf0000160 = CEMB01011940.1 (part of chromosome 17)
# NW_018150973.1 = contig37558 = CEMB01037558.1 = scf000280
# NW_018151224.1 = contig17046 = CEMB01017046.1 = scf000531
# Using this table: https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/900/067/755/GCF_900067755.1_pvi1.1/GCF_900067755.1_pvi1.1_assembly_structure/Primary_Assembly/component_localID2acc
# And gene information from Deakin et al. 2016 (Additional File 5)

synteny_chr_file: config/9_species_config/chromosome_files/GG_chromosomes.list
  # [findZX-synteny] Specify a file with list of chromosomes to only plot these (otherwise leave as "None")

synteny_chr_highlight: [17, 23]
  # [findZX-synteny] Specify chromosomes/scaffolds to highlight in plot type 4, or leave empty


# ================================== #
# Trimming and subsampling of reads  #

## These three variables control trimming and subsampling of reads
## Set all to "false" to disable trimming and subsampling
## Only one variable is allowed to be "true"

trim_reads: true 
  # Set to true for trimming of reads

trim_and_subsample: false
  # Set to true for trimming and subsampling of reads

subsample_only: false
  # Set to true for subsampling of reads (but not trimming)

subsample_basepairs: 
  # Specify the total number of basepairs to extract from both fastq files
  # Will be used if [trim_and_subsample] or [subsample_basepairs] is set to "true"

  # Use this script to calculate expected coverage:
  # ./code/subsampling_cov_calv.sh <REF.fasta> <WANTED_COV> 


# ========================== #
# findZX-specific parameters # 
# ===== (edit if needed) ===== #
 
mismatch_settings: [0.0, 0.2]
  # Genome coverage results will be generated from the original BAM files ("unfiltered"),
  # and two other (modifiable) mismatches settings.
  # "0.0" = 0 mismatches allowed 
  # "0.2" = <=2 mismatches allowed

minSizeScaffold: "10000"
  # The mimimum size of scaffolds in the reference genome to be included in the results


# ============================ #
# External software parameters # 
# ===== (edit if needed) ===== #

params:
  trimmomatic:
  # Control Trimmomatic settings here
    pe:
      trimmer:
        - "LEADING:3"
        - "TRAILING:3"
        - "SLIDINGWINDOW:4:15"
        - "MINLEN:36"
        - "ILLUMINACLIP:workflow/meta/adapters/TruSeq3-PE.fa:2:30:10"